language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - find . -name \*.py -exec pep8 --ignore=E402 {} + 
  - ./manage.py makemigrations && ./manage.py migrate && ./manage.py test
